language: node_js
node_js:
- lts/*
script:
- yarn build
deploy:
- provider: script
  skip_cleanup: true
  script:
  - npx @dhis2/cli-utils release --publish npm
  on:
    tags: false
    branch: master
env:
  global:
  - GIT_AUTHOR_NAME=@dhis2-bot
  - GIT_AUTHOR_EMAIL=apps@dhis2.org
  - GIT_COMMITTER_NAME=@dhis2-bot
  - GIT_COMMITTER_EMAIL=apps@dhis2.org
  - secure: Cr4HCxmC/SkmSDYQd3jGA/po0ISWRTH33QXoo0wcu67y/egxJh5J/3XEd6dpFkKcL4i/W2zFaHd0KhJMp8t39dtQjiGCSsKF7U6NwW7zvZHmLbI2IzYXqawm4AaxKjHmeVrhxoSN91WGZroa9jN+zRXSewjf5BvxXCwkhb7lZWS6rngDr5CWLRbfo4+HfLIwZw/EayPDMLRRdaUCPhvelfcjZnuGy5kar2wLRVg8+fMCVByy7Tm2jN0Di9VMQdxTG97cp+It+oThbmk81FxNzDUJmf+JxI+NEEg4bFY74gtd8ryT2XOWBXJKPjH8ya9bzkn1agsZ65S5rjBXOQmFBDCFAIqt0M5y+F5l3M7rM8qJ87jLh50+oS644amgqSDf/q4XG0wO7lJrn9Uu60UMfm2HhO9wLke+oS+ierbcby2mNRPDrFoBdYSpesOvcP/tC5UhqD8ubzTIRhsw7OTT2JBIW9zsn7JPr0TCpA6oXsIhI6+55CrjEk087lyBfc4r+qTI36sePmyYeMcmPizONO63eYxqU2crkTlukjN5k/UdP6QWhb7CLn9m/l17NuHwSUdxcv2exWJxC+bL+Uv8982N00zpm4zS8TuB9+MKxJAk3EoxKYkJvGJJFVclGRwV5njK9V2nNRU+lF9WEZ1UYBmIQ4wxBg/OoCFbGSwF5I4=
  - secure: hspl/xm2IYfsUosAeMTd/zY24HievmNcgr+kyeZMBSgMKCRqSXt/wsrzq+ohqFM/1GzWE4HLtPZNBDWi9pxC7GoWdEpSPzoKCgULAL2dNXQtW3O6vEFD7mja1pnnLcG/i6fwyRuL+j8O/jRJM7xPUBbYxB3GQ4YjiO0hAWRZTPyoydaOwZLdCE96zmMLGSH0q4G7HxKh+Iys8ySwfpQPi+RlRHeY12MqvR/OaOUID5O2e5LeOf81p2T447UAQuytGL+S828MsNBwiIsLIKnL8F0qmviq4dCB6XrwE0nKpCvoTpXRgSBCw8B5icrOwYhrZf4JjPOJr3qSek0oajb4R3ObSZnpg56+UO9XxcnLgWkGPzUHkjXXEuCJb8al3S2bIPKXXEiFCTtAJy3xj1Mvpnxm75FrldYfwQDNBdx/GZsUd+VLqur9+JgffGaSGEGBz6AHAwrHinpiHWDLqGht9a1nT0CsU+/Yfi+tpeBnG+3YU0pIeAn87aTAE/XQMKjuX4P5Nj84lSi650xT3m9FMx5dgBXAy+jZ+9EtbumUrWIQijtQnEcruEvhrfOwG7/UVnGxmeqaQjrXfMgNLPQocPD2BwbkiP5RgMKYIZCe/U7fe5e0QoLMxI9NLC1rBHohNpKi5GfVZ7Sf12GkZ9lPQ8bJDNAWw7yeZJsODl41H+E=
